### ISSUE TITLE
[Proposal] Extended mailer

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-mailer#16]
This mailer is very simple, I think that many of us need more than that to send their emails, I think of a template management by MJML and EJS combined.

MJML makes it easy to create compatible emails in different clients and EJS makes them dynamic. Here is an example (few lines) of what I started to do:

https://github.com/Oagenda/mails

**Comment by gabrielstuff** [comment]
The goal of this mailer is to mail.
If you need a service which template, I would suggest to create EJS or MJML service which handle that.

**Comment by daffl** [comment]
I usually just do templating with a hook. Something like

```js
app.service('mailer').hooks({
  before: {
    async create(context) {
      const { templateName, body } = context.data;
      const result = await renderTemplate(templateName, body);

      context.data.body = result;

      return context;
    }
  }
});
```
