### ISSUE TITLE
How to handle uncatchable promises error.

### ISSUE THREAD

**Issue by gabrielstuff** [feathersjs/feathers-mailer#17]
Thanks for this really simple to use Mailer. It is really nice to use and works great with SMTP, mandrill or Mailjet (this are the ones, tested so far.)

I have an issue that I do not know how to properly handle without rewriting the service.

When mandrill is not reachable or you misconfigured the service, the Promise after the create will be returned as is and so will never resolve. Instead it fail and throw an error.

As the service only return the promise without catching anything, I do not understand how we are supposed to handle errors at the application level.

Thanks,

### Steps to reproduce

To reproduce: 

1. Develop locally, cut your network connection and try to send to mandrill
2. Misconfigured your smtp value
3. Wait for mandrill to be down (happened a lot recently) :)

### Expected behavior
The error should be catched and the route should response with the correct error code : 

500, 403, what ever

### Actual behavior
The response is never send and client timeout

### System configuration

Simple example app in README over REST POST.

**Module versions** : latest

**NodeJS version**: 8.9.1

**Operating System**: macOS High Sierra

**Browser Version**: Postman / cURL

**Comment by daffl** [comment]
If `nodemailer` just hangs in that case I would think this is probably more of a bug in nodemailer. As longs as the promise reject though, Feathers will return it as a 500 error.
